GET http://localhost:8081/api/smewallets/securityquestions/findAll
Content-Type: application/json

###

POST  http://localhost:8081/api/smewallets/securityquestions/create
Content-Type: application/json

{
"question": "what is your birthday cuz?"
}

###
