GET http://localhost:8081/api/smewallets/passwordresets/findAll
Content-Type: application/json
###

GET http://localhost:8081/api/smewallets/passwordresets/findById/1
Content-Type: application/json
###

POST http://localhost:8081/api/smewallets/passwordresets/create
Content-Type: application/json

{
  "email": "sam@gmail.com",
  "token": "I am a token"
}

###