GET http://localhost:8081/api/smewallets/invites/findAll
Content-Type: application/json
###

GET http://localhost:8081/api/smewallets/invites/findById/1
Content-Type: application/json
###

POST http://localhost:8081/api/smewallets/invites/create
Content-Type: application/json

{
  "user": {
    "id": 1,
    "name": "Okia Jacob",
    "email": "jacob@gmail.com",
    "refUserId": 100,
    "emailVerifiedAtStr": "2020-03-03 10:01:49.192690",
    "password": "passs",
    "phoneNumber": "07005677789",
    "userType": "buyer"
  },
  "inviteCode": "the invite code",
  "name": "Sas",
  "email": "sam@gmail.com"
}

###