GET http://localhost:8081/api/smewallets/wallets/findAll
Content-Type: application/json
###

GET https:// 81.199.16.73/api/smewallets/wallets/findAll
Content-Type: application/json

###


GET http://localhost:8081/api/smewallets/wallets/findById/1
Content-Type: application/json

###

#,"emailVerifiedAt":"2019-11-21 10:01:09.626"

POST http://localhost:8081/api/smewallets/wallets/create
Content-Type: application/json

{
  "name" : "SME",
"user": {
  "id":3,
  "email":"jacob@gmail.com",
  "emailVerifiedAtStr":"2020-03-03 10:01:49.192690",
  "password":"passs",
  "phoneNumber":"07005677789",
  "refUserId":100,
  "name":"Okia Jacob",
  "userType":"buyer"
}

}

###

