# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8081/api/smewallets/invoices/findAll
Content-Type: application/json
###

GET http://localhost:8081/api/smewallets/invoices/findById/1
Content-Type: application/json
###

POST http://localhost:8081/api/smewallets/invoices/create
Content-Type: application/json

{
  "order": {
    "id": "1",
    "isbnNumber": "isbn-45",
    "itemName": "test item name",
    "itemDescription": "the item description",
    "billingAddress": " the billing address",
    "saleUnit": "sale unit",
    "quantity": 2,
    "department": "tye department ",
    "conveyanceMethod": "the conveyance method",
    "deliveryTerms": "the delivery terms",
    "paymentTerms": "the payment terms",
    "placeOfDelivery": "place of delivery",
    "deliveryTime": "2020-01-29 13:37:05",
    "orderDueDate": "2020-01-29 13:37:05",
    "time_period": "30 days",
    "qrCode": "the qr code",
    "orderStatus": "the order status",
    "raiseInvoice": "raise invoice",
    "notificationStatus": "the notification status",
    "timestampStr": "2020-03-18 10:37:23.161940",
    "industryType": "Manufacturing",

    "buyer": {
              "id": 1,
              "name": "Okia Jacob",
              "email": "jacob@gmail.com",
              "refUserId": 100,
              "emailVerifiedAtStr": "2020-03-03 10:01:49.192690",
              "password": "passs",
              "phoneNumber": "07005677789",
              "userType": "buyer"
             },

    "supplier": {
                 "id": 2,
                 "name": "Deb",
                 "email": "deb@gmail.com",
                 "refUserId": 105,
                 "emailVerifiedAtStr": "2020-02-26 08:27:31.116151",
                 "password": "passs",
                 "phoneNumber": "0700",
                 "userType": "supplier"
               },

    "wallet": {
      "id": 1,
      "name": "SME",
      "timestampStr": "2020-03-03 10:30:45.603888",
      "user": {
               "id": 1,
               "name": "Okia Jacob",
               "email": "jacob@gmail.com",
               "refUserId": 100,
               "emailVerifiedAtStr": "2020-03-03 10:01:49.192690",
               "password": "passs",
               "phoneNumber": "07005677789",
               "userType": "buyer"
              }
             }
   },

  "sponsor": {
              "id": 3,
              "email": "tintino@gmail.com",
              "emailVerifiedAtStr": "2019-11-21 10:01:09",
              "password": "jothi",
              "phoneNumber": "0781123456",
              "refUserId": 102,
              "name": "Tin Tin",
              "userType": "sponsor"
            },

  "invoiceDueDateStr": "2020-1-19 7:44:23",
  "invoiceStatus": "Pending",
  "transactionFeePercentage": 5,
  "transactionFees": 10,
  "interestRate": 3,
  "amountToPay": 15,
  "withHoldingAmount": 33,
  "withHoldingTaxPercentage": 10,
  "notificationStatus": "Approved",
  "buyerNotificationStatus": "Accepted",
  "declineReason": "Insufficient Funds",
  "getPaid": 1,
  "authorizeStatus": 1,
  "sponsorStatus": 1,
  "theTimestampStr": "2019-12-30 5:44:23"
}

###

